#!/usr/bin/env ruby
require './flask_set'

amount, capacity, * = ARGV
begin
  p 'flask amount: %d' % amount
  p 'flask capacity: %d' % capacity
rescue TypeError
  p 'Input flask amount [4]: '
  amount = STDIN.gets.chomp
  p 'Input flask capacity [4]: '
  capacity = STDIN.gets.chomp
end

FlaskSet.generator = FlaskSetGenerator.new(amount, capacity)
fs = FlaskSet.new
fs.shuffle 300, silent: true
fs.inspect

p 'Press Enter to resolve or other key to exit.'
if STDIN.gets.chomp === ''
  fs.resolve
else
  p 'Exiting.'
end
